columnSuffix: kcomecgw
contentColumnType: text
fieldGroup: b42af606-7e4a-44cd-97a9-111769690a10 # Common
handle: heroBannerText
instructions: null
name: 'Hero banner text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
